// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgf1Ev6AB4qsiARiwYuZ60pKNhD_OFbBk',
    appId: '1:303243898619:android:0cf1bd5dc168f0e2998a5e',
    messagingSenderId: '303243898619',
    projectId: 'rushgo-99199',
    storageBucket: 'rushgo-99199.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzizBSVK_HywiTS3IM_0ijvTB-Riu9dvk',
    appId: '1:303243898619:web:370ae5d49ef29406998a5e',
    messagingSenderId: '303243898619',
    projectId: 'rushgo-99199',
    authDomain: 'rushgo-99199.firebaseapp.com',
    storageBucket: 'rushgo-99199.firebasestorage.app',
    measurementId: 'G-B4HMKSGGFX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-NuiVGM-ktaypTVv_uYOOaq8zWEQnQQ',
    appId: '1:303243898619:ios:0d94d15ff27820d3998a5e',
    messagingSenderId: '303243898619',
    projectId: 'rushgo-99199',
    storageBucket: 'rushgo-99199.firebasestorage.app',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-NuiVGM-ktaypTVv_uYOOaq8zWEQnQQ',
    appId: '1:303243898619:ios:0d94d15ff27820d3998a5e',
    messagingSenderId: '303243898619',
    projectId: 'rushgo-99199',
    storageBucket: 'rushgo-99199.firebasestorage.app',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzizBSVK_HywiTS3IM_0ijvTB-Riu9dvk',
    appId: '1:303243898619:web:61c67383334e9f4f998a5e',
    messagingSenderId: '303243898619',
    projectId: 'rushgo-99199',
    authDomain: 'rushgo-99199.firebaseapp.com',
    storageBucket: 'rushgo-99199.firebasestorage.app',
    measurementId: 'G-1ZJME5P2WD',
  );
}